name: Build Redirects

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate redirect pages
        run: |
          import yaml, os
          from pathlib import Path

          with open("redirects.yml", encoding="utf-8") as f:
              redirects = yaml.safe_load(f)

          template = Path("template.html").read_text(encoding="utf-8")

          outdir = Path("dist")
          outdir.mkdir(exist_ok=True)

          for slug, url in redirects.items():
              d = outdir / slug
              d.mkdir(parents=True, exist_ok=True)
              html = template.replace("{{slug}}", slug).replace("{{url}}", url)
              (d / "index.html").write_text(html, encoding="utf-8")

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
